name = "logical-mechanism/Seedelf-Wallet"
version = "0.3.6"
compiler = "v1.1.9"
plutus = "v3"
license = "MIT"
description = "Seedelf: A Cardano Stealth Wallet"

[repository]
user = "logical-mechanism"
project = "Seedelf-Wallet"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]